version: '3.8'

services:
  api:
    build: .
    command: python api.py
    # УБИРАЕМ ports: "8000:8000". 
    # Теперь API доступен только ДРУГИМ контейнерам по внутренней сети
    volumes:
      - .:/app
    restart: unless-stopped
    env_file: .env

  bot:
    build: .
    command: python main.py
    depends_on:
      - api
    volumes:
      - .:/app
    restart: unless-stopped
    env_file: .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - default
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-app.rule=Host(`canteen.thompson.uz`)"
      - "traefik.http.routers.web-app.entrypoints=websecure"
      - "traefik.http.routers.web-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.web-app.loadbalancer.server.port=80"

networks:
  default:
  traefik-net:
    external: true
    name: web
